### PR TITLE
Allow for data binded events to be displayed

### PR DESCRIPTION
**Pull request by threeaccents**
I also added a gitignore file. And fixed a small typo. If everything here seems good would you want me to squash the commits?

### CODE REVIEW

**Comment by HaithemMosbahi** [comment]
The idea of observer and the way you refetch events seem good.
However, If you take a look at the _initialize method, which initialize the scheduler component, you will notice that when adding events to the calendar I'm making a call to a method called _updateEvents which update events's data based on the scheduler options. For example, if the user has chosen to use the concept of categories, we should iterate over the list of events in order to set the background color based on the category color. Thus, I think we should take that into consideration. For now, i can merge your PR and i will update the code to handle the case of events with categories.

**Comment by HaithemMosbahi** [comment]
I have a question about _eventsChanged method.
I think, there are some cases where the first call of this method is made before the invocation of ready() method. Thus, the observer method will fail because this._scheduler is still undefined.
Do you have this scenario in your use case ?

**Comment by threeaccents** [comment]
So to address the first issue would something like work?

```
this._scheduler.fullCalendar('removeEvents');
let schedulerEvents = this._updateEvents(this.events);
this._scheduler.fullCalendar('addEventSource', { events: schedulerEvents, color: this.eventColor, textColor: this.textColor });
```

As far `this._scheduler` being undefined I thought of the same thing when writing the code; however, from my understanding is that changing the `events` property, from another component, would be impossible since the component must finish its connect life cycle for it to be accessible by another component. So the only way that function gets called prior to the ready function is if we internally change it before the ready function. If that is not the case and my understanding is incorrect then I guess I see 2 options. The first being just adding a simple if statement to the function to check if `this._scheduler` is set. Negatives to that is that the component will essentially "lose" the new events value and never update the calendar with the new events. Second option to not lose the events value is just to keep bubbling up the event until `this._scheduler` is set. The second option is seems very hacky and could be the cause of future bugs.

**Comment by HaithemMosbahi** [comment]
Yes that would resolve the first issue. Then, We could refactor this by moving the code that updates the events array in method called refetchEvents, so we can invoke it whenever the events property changes.

For the issue of this._scheduler being undefined. I have a use case where the observer function gets called prior the the ready function :
* First, I've initialized the scheduler-component with an array of two events.
* Second, When a user clicks on a button from an outer component, a new set of events 
is passed to the scheduler.

What happens here : 
The _eventsChanged function has been called before the ready function 

How I resolve it :
I've been thinking if we could ignore the first call to the observer function, something like this : 
```js
 _eventsChanged(newValue, oldValue) {
        // make sure that the newValue is not undefined. 
        // For thr first call, the oldValue will have the currentValue of the property
        // newValue will be undefined
        if (newValue) {
          // update goes here
        }
      }
```
The first value of the events property will be handled when initializing the scheduler component ( in the ready function ). Then, the next changes will be handled by the observer function.

I propose that we merge this PR, Then we will improve it by testing different use cases.
What do you think ?

**Comment by threeaccents** [comment]
Hey man so I've made the updates we spoke of. I also added a `_removeEvents()` method to just to have a consistent api when dealing with the scheduler. I think it's ready to be merged in and as you said make incremental improvements as we use it more.

**Comment by HaithemMosbahi** [comment]
I've made a mistake when I've explained the _eventsChanged function with oldValue and newValue arguments.
For the first call, the newValue arg will have the current value of the property, while the oldValue will be resolved as undefined : make sense now :D 
The observer function looks like this : 
```js
_eventsChanged(newValue, oldValue) {
        // make sure that the oldValue is not undefined. 
        // For thr first call, the newValue will have the currentValue of the property
        // oldValue will be undefined
        if (oldValue) {
          this._removeEvents();
          this._refetchEvents();
        }
      }
```
I just tested your PR, and it worked as expected 👍

**Pull request merged**
