### PR TITLE
fix for polymer lint on components and removed invalid test case

### PR DESCRIPTION
**Pull request by sbonnick**
Noticed the builds were breaking due to linting errors. added a few comments in the code to resolve the lint errors and removed an invalid test trying to build a "full-calendar" component.

### CODE REVIEW

**Comment by sbonnick** [comment]
hummm looks like the fix for "polymer lint" does not help with the errors in the build from "polylint"

**Comment by sbonnick** [comment]
any thoughts to installing the full polymer-cli using NPM and using it to run the tests and lint?

**Comment by HaithemMosbahi** [comment]
Yes ! I think that would fix the travis build issue. 
With your latest commit the polymerlint issue is resolved. Now the build fails because the test has failed

**Comment by sbonnick** [comment]
ok so this should fix all the build breaks, there is a test failing but it looks very much like a legit test failure. This is currently using wct, but after the test is fixed, it may make sense to switch to "polymer test". That way the same tooling a dev would run locally will run in the build process.

**Comment by HaithemMosbahi** [comment]
I think we should keep the basic test. I just forgot to change the element tag in my test file when I renamed the component. The test is failing because the first test case didn't find the test-fixture element with id="BasicTestFixture"

**Comment by sbonnick** [comment]
so just pushed a change with the basic test back in. also noticed test failures related to setup vs legit issues. So now, the second test correctly fails due to actual problems - one of them being the issue I fixed in a separate PR. still, fails on some other parameters that I don't think have valid defaults.

failures which my other PR should fix:
     view.activeRange is undefined

someone will want to look at these cases to evaluate good defaults or adjust test to supply values for them.

**Comment by sbonnick** [comment]
yep, looks like the view.activeRange failures are gone in this merge vs my local - which makes sense because I fixed it already on master. 

The other failures can be resolved with setting defaults. I know when I use this element I give "events" and "categories" a default of [] to avoid some of these failures.

**Comment by sbonnick** [comment]
BAM, all green. ;)

**Comment by HaithemMosbahi** [comment]
Great 😃 ! good job @sbonnick ;)
I am gonna merge this PR

**Pull request merged**
